//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.CurrencyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyService.IConvertService")]
    public interface IConvertService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertService/GetCurrencyInWords", ReplyAction="http://tempuri.org/IConvertService/GetCurrencyInWordsResponse")]
        string GetCurrencyInWords(string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvertService/GetCurrencyInWords", ReplyAction="http://tempuri.org/IConvertService/GetCurrencyInWordsResponse")]
        System.Threading.Tasks.Task<string> GetCurrencyInWordsAsync(string amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvertServiceChannel : WpfClient.CurrencyService.IConvertService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertServiceClient : System.ServiceModel.ClientBase<WpfClient.CurrencyService.IConvertService>, WpfClient.CurrencyService.IConvertService {
        
        public ConvertServiceClient() {
        }
        
        public ConvertServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCurrencyInWords(string amount) {
            return base.Channel.GetCurrencyInWords(amount);
        }
        
        public System.Threading.Tasks.Task<string> GetCurrencyInWordsAsync(string amount) {
            return base.Channel.GetCurrencyInWordsAsync(amount);
        }
    }
}
